// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/inventory/v1/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSeatsRequest) Reset() {
	*x = LockSeatsRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSeatsRequest) ProtoMessage() {}

func (x *LockSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSeatsRequest.ProtoReflect.Descriptor instead.
func (*LockSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *LockSeatsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LockSeatsRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *LockSeatsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type LockSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSeatsResponse) Reset() {
	*x = LockSeatsResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSeatsResponse) ProtoMessage() {}

func (x *LockSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSeatsResponse.ProtoReflect.Descriptor instead.
func (*LockSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *LockSeatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LockSeatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\"proto/inventory/v1/inventory.proto\x12\finventory.v1\"c\n" +
	"\x10LockSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\"C\n" +
	"\x11LockSeatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2`\n" +
	"\x10InventoryService\x12L\n" +
	"\tLockSeats\x12\x1e.inventory.v1.LockSeatsRequest\x1a\x1f.inventory.v1.LockSeatsResponseBDZBgithub.com/DipeshC1707/BookYourShow/proto/inventory/v1;inventorypbb\x06proto3"

var (
	file_proto_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_v1_inventory_proto_rawDescData []byte
)

func file_proto_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_v1_inventory_proto_rawDescData
}

var file_proto_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inventory_v1_inventory_proto_goTypes = []any{
	(*LockSeatsRequest)(nil),  // 0: inventory.v1.LockSeatsRequest
	(*LockSeatsResponse)(nil), // 1: inventory.v1.LockSeatsResponse
}
var file_proto_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.InventoryService.LockSeats:input_type -> inventory.v1.LockSeatsRequest
	1, // 1: inventory.v1.InventoryService.LockSeats:output_type -> inventory.v1.LockSeatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_v1_inventory_proto_init() }
func file_proto_inventory_v1_inventory_proto_init() {
	if File_proto_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_v1_inventory_proto = out.File
	file_proto_inventory_v1_inventory_proto_goTypes = nil
	file_proto_inventory_v1_inventory_proto_depIdxs = nil
}
