// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/booking/v1/booking.proto

package bookingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateBookingRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *CreateBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ConfirmBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingRequest) Reset() {
	*x = ConfirmBookingRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingRequest) ProtoMessage() {}

func (x *ConfirmBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ConfirmBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingResponse) Reset() {
	*x = ConfirmBookingResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingResponse) ProtoMessage() {}

func (x *ConfirmBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_booking_v1_booking_proto protoreflect.FileDescriptor

const file_proto_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/booking/v1/booking.proto\x12\n" +
	"booking.v1\"e\n" +
	"\x14CreateBookingRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"6\n" +
	"\x15CreateBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"6\n" +
	"\x15ConfirmBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"2\n" +
	"\x16ConfirmBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbf\x01\n" +
	"\x0eBookingService\x12T\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a!.booking.v1.CreateBookingResponse\x12W\n" +
	"\x0eConfirmBooking\x12!.booking.v1.ConfirmBookingRequest\x1a\".booking.v1.ConfirmBookingResponseB@Z>github.com/DipeshC1707/BookYourShow/proto/booking/v1;bookingpbb\x06proto3"

var (
	file_proto_booking_v1_booking_proto_rawDescOnce sync.Once
	file_proto_booking_v1_booking_proto_rawDescData []byte
)

func file_proto_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_v1_booking_proto_rawDesc), len(file_proto_booking_v1_booking_proto_rawDesc)))
	})
	return file_proto_booking_v1_booking_proto_rawDescData
}

var file_proto_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_booking_v1_booking_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),   // 0: booking.v1.CreateBookingRequest
	(*CreateBookingResponse)(nil),  // 1: booking.v1.CreateBookingResponse
	(*ConfirmBookingRequest)(nil),  // 2: booking.v1.ConfirmBookingRequest
	(*ConfirmBookingResponse)(nil), // 3: booking.v1.ConfirmBookingResponse
}
var file_proto_booking_v1_booking_proto_depIdxs = []int32{
	0, // 0: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	2, // 1: booking.v1.BookingService.ConfirmBooking:input_type -> booking.v1.ConfirmBookingRequest
	1, // 2: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.CreateBookingResponse
	3, // 3: booking.v1.BookingService.ConfirmBooking:output_type -> booking.v1.ConfirmBookingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_booking_v1_booking_proto_init() }
func file_proto_booking_v1_booking_proto_init() {
	if File_proto_booking_v1_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_v1_booking_proto_rawDesc), len(file_proto_booking_v1_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_v1_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_v1_booking_proto = out.File
	file_proto_booking_v1_booking_proto_goTypes = nil
	file_proto_booking_v1_booking_proto_depIdxs = nil
}
